replicaCount: 1
app: ksm-pgr-services
namespace: egov

image:
  repository: ksm-pgr-services
  pullPolicy: Always
  name: 569197888283.dkr.ecr.ap-south-1.amazonaws.com/ksm-pgr-services-prod
  tag: latest

application:
  config:
    mdms_url: ksm-core-mdm-service:8080/egov-mdms-service
    idgen_url: ksm-core-idgen-service:8080/idgen-services
    file_url: ksm-kfm-file-services:8080/file-management-services
    dmdm_url: ksm-core-dmdm-service:8080/dmdm-services
    pdf_url: ksm-core-pdf-service:8080/pdf-service
    sms_url: ksm-core-sms-service:8080/sms-service
    otp_url: ksm-core-otp-service:8080/otp-service
    urlshortening_url: ksm-core-url-service:8080/u
    file_create_topic: file.create.prod
    file_update_topic: file.update.prod
    file_resubmit_topic : file.resubmit.prod
    database_url: jdbc:postgresql://ksm-pgr-services-db-prod-20231228190839501700000001.ccljsus1zvuc.ap-south-1.rds.amazonaws.com:5432/pgr_prod?ssl=true&sslmode=require
    database_user: app_user
    service_bucket: ksm-pgr-services-prod
    region: ap-south-1
    cdn_lb_url: https://cdn.ksmart.lsgkerala.gov.in/ulb-logos/
    petition_lb_url: https://ksmart.lsgkerala.gov.in/ui/pgr/public/summary/
    whatsapp_lb_url: https://dev.ksmart.live/pgr-services/pgr/download
    delete_lb_url: https://api.ksmart.lsgkerala.gov.in/pgr-services/
    edit_lb_url: https://api.ksmart.lsgkerala.gov.in/ui/
    domain_url: api.ksmart.lsgkerala.gov.in
    kafka_servers: b-3.kafkaprod.vhbzq2.c2.kafka.ap-south-1.amazonaws.com:9094,b-2.kafkaprod.vhbzq2.c2.kafka.ap-south-1.amazonaws.com:9094,b-1.kafkaprod.vhbzq2.c2.kafka.ap-south-1.amazonaws.com:9094
    profile: prod

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ksm-pgr-services
  roleArn: "arn:aws:iam::569197888283:role/ksm-pgr-services-role-prod"

podAnnotations: { }

secretMap:
  name: ksm-pgr-services

podSecurityContext: { }

securityContext: { }

service:
  port: 8080
  targetPort: 8080
  targetGroupARN: "arn:aws:elasticloadbalancing:ap-south-1:569197888283:targetgroup/ksm-pgr-services-prod/547b0eae3e34c551"

resources:
 requests:
   memory: "2000Mi"
   cpu: "1000m"
 limits:
   memory: "2000Mi"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

nodeSelector: { }

tolerations: [ ]

affinity: { }
