replicaCount: 1
app: ksm-pgr-services
namespace: egov

image:
  repository: ksm-pgr-services
  pullPolicy: Always
  name: 095566081345.dkr.ecr.ap-south-1.amazonaws.com/ksm-pgr-services-dev
  tag: latest

application:
  config:
    mdms_url: ksm-core-mdm-service:8080/egov-mdms-service
    idgen_url: ksm-core-idgen-service:8080/idgen-services
    file_url: ksm-kfm-file-services:8080/file-management-services
    dmdm_url: ksm-core-dmdm-service:8080/dmdm-services
    pdf_url: ksm-core-pdf-service:8080/pdf-service
    sms_api_url: ksm-core-sms-service:8080/sms-service
    otp_url: ksm-core-otp-service:8080/otp-service
    urlshortening_url: ksm-core-url-service:8080/u
    file_create_topic: file.create.dev
    file_update_topic: file.update.dev
    file_resubmit_topic : file.resubmit.dev
    database_url: jdbc:postgresql://ksm-pgr-services-db-dev-20230912000113835500000001.cjmsejiyf6ey.ap-south-1.rds.amazonaws.com:5432/pgr_dev?ssl=true&sslmode=require
    database_user: app_user
    service_bucket: ksm-pgr-services-dev
    feedback_bucket: ksm-pgr-services-dev/feedback
    report_bucket: ksm-pgr-reports-services-dev
    data_bucket: ksm-reporting-data-dev
    region: ap-south-1
    cdn_lb_url: https://dev.cdn.ksmart.live/ulb-logos/
    petition_lb_url: https://dev.ksmart.live/ui/pgr/public/summary/
    whatsapp_lb_url: https://dev.api.ksmart.live/pgr-services/pgr/download
    delete_lb_url: https://dev.api.ksmart.live/pgr-services/
    edit_lb_url: https://dev.api.ksmart.live/ui/
    domain_url: dev.api.ksmart.live
    kafka_servers: b-1.kafkadev.77zusa.c2.kafka.ap-south-1.amazonaws.com:9094,b-2.kafkadev.77zusa.c2.kafka.ap-south-1.amazonaws.com:9094,b-3.kafkadev.77zusa.c2.kafka.ap-south-1.amazonaws.com:9094
    profile: dev

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ksm-pgr-services
  roleArn: "arn:aws:iam::095566081345:role/ksm-pgr-services-role-dev"

podAnnotations: { }

secretMap:
  name: ksm-pgr-services

podSecurityContext: { }

securityContext: { }

service:
  port: 8080
  targetPort: 8080
  targetGroupARN: "arn:aws:elasticloadbalancing:ap-south-1:095566081345:targetgroup/ksm-pgr-services-dev/0dc3976a4617cc5b"

resources:
  requests:
    memory: "2000Mi"
    cpu: "500m"
  limits:
    memory: "2000Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }
